package style

import (
	"slices"

	"fyne.io/fyne/v2"
	"github.com/s-daehling/fyne-charts/internal/style"
)

// NewColorPaletteTheme creates a fyne theme that is able to interpret fyne.ThemeColorName generated by ColorPalette
// defTheme is the default theme that is used for all colors that are not interpreted by this theme
func NewColorPaletteTheme(defTheme fyne.Theme) (th fyne.Theme) {
	th = style.NewColorPaletteTheme(defTheme)
	return
}

// ColorPalette stores fyne.ThemeColorNames
type ColorPalette struct {
	i        int
	colNames []fyne.ThemeColorName
}

// Next gives the next fyne.ThemeColorName
func (p *ColorPalette) Next() (colName fyne.ThemeColorName) {
	if len(p.colNames) == 0 {
		colName = fyne.ThemeColorName("")
		return
	}
	p.i++
	if p.i == len(p.colNames) {
		p.i = 0
	}
	colName = p.colNames[p.i]
	return
}

// Prevoius gives the previous fyne.ThemeColorName
func (p *ColorPalette) Prevoius() (colName fyne.ThemeColorName) {
	if len(p.colNames) == 0 {
		colName = fyne.ThemeColorName("")
		return
	}
	p.i--
	if p.i < 0 {
		p.i = len(p.colNames) - 1
	}
	colName = p.colNames[p.i]
	return
}

// Add adds one fyne.ThemeColorName at the end of the palette
func (p *ColorPalette) Add(colName fyne.ThemeColorName) {
	p.colNames = append(p.colNames, colName)
}

// Remove removes the fyne.ThemeColorName from the palette, if it exists
func (p *ColorPalette) Remove(colName fyne.ThemeColorName) {
	p.colNames = slices.DeleteFunc(p.colNames, func(e fyne.ThemeColorName) bool {
		return e == colName
	})
}

// Names returns a slice containing all fyne.ThemeColorNames stored in the palette
func (p *ColorPalette) Names() (n []fyne.ThemeColorName) {
	n = append(n, p.colNames...)
	return
}

// NewPaletteLightDark returns a ColorPalette containing one light and one dark variant of base color
func NewPaletteLightDark(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteLightDark(base),
	}
	return
}

// NewPaletteLightDarkSet returns a ColorPalette containing one light and one dark variant of each base color
func NewPaletteLightDarkSet(base []fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteLightDarkSet(base),
	}
	return
}

// NewPaletteLightMediumDark returns a ColorPalette containing one light, one medium and one dark variant of base
func NewPaletteLightMediumDark(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteLightMediumDark(base),
	}
	return
}

func NewPaletteLightMediumDarkSet(base []fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteLightMediumDarkSet(base),
	}
	return
}

// NewPaletteDivergentLightMediumDark returns a ColorPalette containing one light, one medium and one dark variant of base1, a neutral color and the same variants as for base1 in different order for base2
func NewPaletteDivergentLightMediumDark(base1 fyne.ThemeColorName, base2 fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteDivergentLightMediumDark(base1, base2),
	}
	return
}

// NewPaletteComplementary returns a ColorPalette containing base and the complementary color in HSL
func NewPaletteComplementary(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteComplementary(base),
	}
	return
}

// NewPaletteTriadic returns a ColorPalette containing base and two colors with a distance of 120° in HSL space
func NewPaletteTriadic(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteTriadic(base),
	}
	return
}

// NewPaletteQuadratic returns a ColorPalette containing base and three colors with a distance of 90° in HSL space
func NewPaletteQuadratic(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteQuadratic(base),
	}
	return
}

// NewPaletteHexadic returns a ColorPalette containing base and five colors with a distance of 60° in HSL space
func NewPaletteHexadic(base fyne.ThemeColorName) (p *ColorPalette) {
	p = &ColorPalette{
		i:        -1,
		colNames: style.NewPaletteHexadic(base),
	}
	return
}

// // NewPaletteAnalogousThree returns a ColorPalette containing base and two colors with a distance of +/- 45° in HSL space centered around base
// func NewPaletteAnalogousThree(base fyne.ThemeColorName) (p *ColorPalette) {
// 	p = &ColorPalette{
// 		i:        -1,
// 		colNames: style.NewPaletteAnalogousThree(base),
// 	}
// 	return
// }

// // NewPaletteAnalogousFive returns a ColorPalette containing base and four colors with a distance of +/- 45° in HSL space centered around base
// func NewPaletteAnalogousFive(base fyne.ThemeColorName) (p *ColorPalette) {
// 	p = &ColorPalette{
// 		i:        -1,
// 		colNames: style.NewPaletteAnalogousFive(base),
// 	}
// 	return
// }
